### ISSUE TITLE
--no-sasl.handshake not working

### ISSUE THREAD

**Issue by Ga11u** [danielqsj/kafka_exporter#272]
The danielqsj/kafka-exporter:latest latest version produces an error when using ``--no-sasl.handshake`` . It was not happening before.
The log:
```
flag provided but not defined: -no-sasl.handshake
Usage of /bin/kafka_exporter:
  -alsologtostderr
      log to standard error as well as files
...
```

The docker-compose definition:
```
  kafka_exporter:
    image: danielqsj/kafka-exporter
    <<: *network-base
    ports:
    - published: 9308
      target: 9308 
    command: 
      - "--kafka.server=tasks.kafka1:9192"
      - "--kafka.server=tasks.kafka2:9292"
      - "--kafka.server=tasks.kafka3:9392"
      - "--no-sasl.handshake"  
    deploy:
      placement:
        constraints:
          - node.role==manager
      labels:
        - prometheus-job=kafka_exporter 
        - scrape-port=9308
```

Any ideas on what could happen? The same declaration was working fine before.

Thank you
