### ISSUE TITLE
sasl.password as Env variable to hide from ps output 

### ISSUE THREAD

**Issue by shahsaifi** [danielqsj/kafka_exporter#293]
Is there a way to pass "sasl.password" as a environment variable either for docker container/systemd/command line to hide password getting listed in process output "ps".

**Comment by ndallavalentina** [comment]
probably you want to reference a password as an env variable from secret:
```
        env:
        - name: MY_SECRET
          valueFrom:
            secretKeyRef:
              name: this-is-my-secret
              key: password
```
then 
`--sasl.password=$(MY_SECRET)` use () not {} as it's sh
