### ISSUE TITLE
Error using boolean flags

### ISSUE THREAD

**Issue by orlandoburli** [danielqsj/kafka_exporter#366]
# Scenario
All scenario I try to pass a boolean argument, like `use.consumelag.zookeeper`, returns this error:

```golang
2023-02-02 13:48:54 kafka_exporter: error: unexpected true, try --help
```

I've tried to run with those parameters:

```
--kafka.server=localhost:9092 --verbosity=5 --zookeeper.server=localhost:2128 --use.consumelag.zookeeper=true
```

This error happens when you try to run as a docker image or a binary.

Also I tried to run the source code, and it looks like it's an error with the [kingpin](https://github.com/alecthomas/kingpin) library. The error happens on this [code line](https://github.com/danielqsj/kafka_exporter/blob/master/kafka_exporter.go#L756).

Another important information: I'm running on a MacOS with M1 processor, not sure if it's related.

**Comment by orlandoburli** [comment]
Update: turns out that that the problem was in the docker-compose file. You need to configure the kafka to respond as the host `kafka` (same name in the docker file). Some kind of rever DNS.

Final docker-compose file:

```yaml
version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks: 
      - project-kafka-scale
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks: 
      - project-kafka-scale
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka

  kafka_exporter:
    image: danielqsj/kafka-exporter:latest
    depends_on:
      - kafka
      - zookeeper
    ports:
      - 9308:9308
    networks:
      - project-kafka-scale
    command: --kafka.server=kafka:9092 --verbosity=5 --zookeeper.server=zookeeper:2181 --use.consumelag.zookeeper
    deploy:
      mode: replicated
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M      
      replicas: 1
      endpoint_mode: vip


networks: 
  project-kafka-scale:
    driver: bridge

```
