### ISSUE TITLE
Error: "Templating: Failed to upgrade legacy queries"

### ISSUE THREAD

**Issue by muzammil360** [danielqsj/kafka_exporter#428]
Hi @danielqsj, I am getting the error "Templating: Failed to upgrade legacy queries" when i import the dashboard using `GrafanaDashboard` custom resource in k8s. If i import the dashboard via GUI, it works fine. Do you know what might be going wrong here?  

<img width="1438" alt="image" src="https://github.com/danielqsj/kafka_exporter/assets/20393633/60c9cd77-72d7-401d-b59e-033f3c39f560">

**Comment by muzammil360** [comment]
Ok. i found the issue. You are using `DS_PROMETHEUS_WH211` as the variable name. I need to explicitly set value to it. 
Here is what my CRD. 

```
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: kafka
spec:
  folder: default
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasources:
    - inputName: "DS_PROMETHEUS_WH211"
      datasourceName: "Prometheus" 
  grafanaCom:
    id: 7589
    revision: 5
---
```
