### ISSUE TITLE
Kafka Exporter Connection Error: "client has run out of available brokers to talk to"

### ISSUE THREAD

**Issue by ZancheITS** [danielqsj/kafka_exporter#479]
We are experiencing a connection issue with the kafka-exporter where it fails to connect to the Kafka brokers. Despite the configuration in the kafka-exporter.yaml file correctly specifying the Kafka server as user-cluster-kafka-bootstrap:9092, the logs show the error: "Error Init Kafka Client: kafka: client has run out of available brokers to talk to: dial tcp: lookup kafka-server on 10.43.0.10:53: server misbehaving". It seems that the server name is not being resolved correctly. We have verified the deployment configuration and network connectivity, but the issue persists. We are seeking assistance to resolve this connection problem.

CODE: 

replicaCount: 1

image:
  repository: danielqsj/kafka-exporter
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9308

kafkaExporter:
  kafka:
    servers:
      - user-cluster-kafka-bootstrap:9092

  sasl:
    enabled: false
    handshake: true
    username: ""
    password: ""
    mechanism: ""

  tls:
    enabled: false
    insecureSkipTlsVerify: false
    caFile: ""
    certFile: ""
    keyFile: ""

  log:
    verbosity: 0
    enableSarama: false

prometheus:
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: "30s"
    additionalLabels:
      app: kafka-exporter
    metricRelabelings: {}

labels: {}
podLabels: {}
datadog:
  use_datadog: false
  prefix: <dd_prefix>
  metrics: [
    {"kafka_brokers": "kafka_brokers"},
    {"kafka_consumergroup_lag": "kafka_consumergroup_lag"},
    {"kafka_consumergroup_current_offset": "kafka_consumergroup_current_offset"}
    ]

azuremanagedprometheus:
  use_azuremanagedprometheus: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

**Comment by ryanjbonnell** [comment]
If you're using Docker, the error message you're seeing may be due to the Kafka Exporter container starting up _before_ the Kafka cluster container is available.

A typical solution to [controlling the startup order in Docker](https://docs.docker.com/compose/how-tos/startup-order/) is using the `depends_on` attribute and declaring the service to use a healthcheck.

Here's an abbreviated `docker-compose.yml` example:

```yaml
kafka:
  image: bitnami/kafka:latest
  user: root
  container_name: kafka
  hostname: broker
  ports:
    - 9092:9092
    - 9094:9094
  environment:
    - KAFKA_CFG_NODE_ID=0
    - KAFKA_CFG_PROCESS_ROLES=controller,broker
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9093
    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
  healthcheck:
    test: kafka-topics.sh --list --bootstrap-server localhost:9092 || exit 1
    interval: 1s
    timeout: 15s
    retries: 3

kafka-exporter:
  image: danielqsj/kafka-exporter
  command: ["--kafka.server=kafka:9092"]
  ports:
    - 9308:9308
  depends_on:
    kafka:
      condition: service_healthy
  healthcheck:
    test: CMD wget -q -O /dev/null http://localhost:9308/metrics || exit 1
    interval: 30s
    timeout: 10s
    retries: 3
```

You'll also want to **ensure the two containers are in the same Docker network** so they can reach each other by their service name.
