### ISSUE TITLE
cannot get any metrics

### ISSUE THREAD

**Issue by akdj** [danielqsj/kafka_exporter#80]
Hi, 

I tried to use the kafka exporter for monitoring. 

however, I cannot get any metrics. I am using docker compose for starting services, could you help me to check my docker compose script?  Kafka seems to be running well.

docker-compose:
```
version: '2.0'

services:
  zookeeper_service:
    image: docker.rd.softathome.com/zookeeper/wurstmeister/zookeeper:3.4.9
    container_name: zookeeper
    hostname: zookeeper_service
    ports:
      - "2181:2181"
    volumes:
      - /home/cloud/docker/kafka_zookeeper/zookeeper_data:/data
    networks:
        kafka_zookeeper_network:
          ipv4_address: 10.5.0.3

  kafka_service:
    image: docker.rd.softathome.com/kafka/wurstmeister/kafka:2.1.1
    container_name: kafka
    ports:
      - "9094:9094"
      - "7778:7778"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://KAFKA_HOSTMACHINE_IP:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper_service:2181"
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "cpe_device_event:5:1,cpe_status_event:5:1,cpe_invocation_event:5:1,cpe_invocation_event_reply:5:1,cpe_vdev_event:3:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
      - /home/cloud/docker/kafka_zookeeper/kafka_data:/var/lib/kafka/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper_service
    networks:
        kafka_zookeeper_network:
          ipv4_address: 10.5.0.5

  kafka_exporter:
    image: docker.rd.softathome.com/danielqsj/kafka-exporter:1.2.0
    container_name: kafka_exporter
    command: --kafka.server=10.5.0.5:9094
    ports: 
      - "9308:9308"
    depends_on:
      - kafka_service
    networks:
        kafka_zookeeper_network:
          ipv4_address: 10.5.0.8

networks:
  kafka_zookeeper_network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
```

kafka exporter logs:
```
time="2018-11-30T10:42:11Z" level=info msg="Starting kafka_exporter (version=1.2.0, branch=HEAD, revision=5fb725fd1933a83d654194ffc8cf22254ec0f3a9)" source="kafka_exporter.go:475"
time="2018-11-30T10:42:11Z" level=info msg="Build context (go=go1.9, user=travis@travis-job-418981c5-7f03-48cb-b74a-e7640fb024e3, date=20181112-12:40:58)" source="kafka_exporter.go:476"
time="2018-11-30T10:42:11Z" level=info msg="Done Init Clients" source="kafka_exporter.go:174"
time="2018-11-30T10:42:11Z" level=info msg="Listening on :9308" source="kafka_exporter.go:599"
time="2018-11-30T10:42:14Z" level=error msg="Cannot get current offset of topic cpe_invocation_event partition 0: dial tcp: lookup KAFKA_HOSTMACHINE_IP on 127.0.0.11:53: no such host" source="kafka_exporter.go:250"
time="2018-11-30T10:42:14Z" level=error msg="Cannot get current offset of topic cpe_device_event partition 0: dial tcp: lookup KAFKA_HOSTMACHINE_IP on 127.0.0.11:53: no such host" source="kafka_exporter.go:250"
time="2018-11-30T10:42:14Z" level=error msg="Cannot get current offset of topic cpe_invocation_event_reply partition 0: dial tcp: lookup KAFKA_HOSTMACHINE_IP on 127.0.0.11:53: no such host" source="kafka_exporter.go:250"
time="2018-11-30T10:42:14Z" level=error msg="Cannot get current offset of topic cpe_vdev_event partition 0: dial tcp: lookup KAFKA_HOSTMACHINE_IP on 127.0.0.11:53: no such host" source="kafka_exporter.go:250"
time="2018-11-30T10:42:14Z" level=error msg="Cannot get current offset of topic cpe_status_event partition 0: dial tcp: lookup KAFKA_HOSTMACHINE_IP on 127.0.0.11:53: no such host" source="kafka_exporter.go:250"
time="2018-11-30T10:42:14Z" level=error msg="Cannot get oldest offset of topic cpe_invocation_event partition 0: dial tcp: lookup KAFKA_HOSTMACHINE_IP on 127.0.0.11:53: no such host" source="kafka_exporter.go:262"
time="2018-11-30T10:42:14Z" level=error msg="Cannot get oldest offset of topic cpe_device_event partition 0: dial tcp: lookup KAFKA_HOSTMACHINE_IP on 127.0.0.11:53: no such host" source="kafka_exporter.go:262"
time="2018-11-30T10:42:14Z" level=error msg="Cannot get oldest offset of topic cpe_invocation_event_reply partition 0: dial tcp: lookup KAFKA_HOSTMACHINE_IP on 127.0.0.11:53: no such host" source="kafka_exporter.go:262"
time="2018-11-30T10:42:14Z" level=error msg="Cannot get oldest offset of topic cpe_vdev_event partition 0: dial tcp: lookup KAFKA_HOSTMACHINE_IP on 127.0.0.11:53: no such host" source="kafka_exporter.go:262"
time="2018-11-30T10:42:14Z" level=error msg="Cannot get oldest offset of topic cpe_status_event partition 0: dial tcp: lookup KAFKA_HOSTMACHINE_IP on 127.0.0.11:53: no such host" source="kafka_exporter.go:262"
time="2018-11-30T10:42:15Z" level=error msg="Cannot get current offset of topic cpe_invocation_event partition 1: dial tcp: lookup KAFKA_HOSTMACHINE_IP on 127.0.0.11:53: no such host" source="kafka_exporter.go:250"
time="2018-11-30T10:42:15Z" level=error msg="Cannot get current offset of topic cpe_device_event partition 1: dial tcp: lookup KAFKA_HOSTMACHINE_IP on 127.0.0.11:53: no such host" source="kafka_exporter.go:250"
time="2018-11-30T10:42:15Z" level=error msg="Cannot get current offset of topic cpe_invocation_event_reply partition 1: dial tcp: lookup KAFKA_HOSTMACHINE_IP on 127.0.0.11:53: no such host" source="kafka_exporter.go:250"
time="2018-11-30T10:42:15Z" level=error msg="Cannot get current offset of topic cpe_vdev_event partition 1: dial tcp: lookup KAFKA_HOSTMACHINE_IP on 127.0.0.11:53: no such host" source="kafka_exporter.go:250"
time="2018-11-30T10:42:15Z" level=error msg="Cannot get current offset of topic cpe_status_event partition 1: dial tcp: lookup KAFKA_HOSTMACHINE_IP on 127.0.0.11:53: no such host" source="kafka_exporter.go:250"
time="2018-11-30T10:42:15Z" level=error msg="Cannot get oldest offset of topic cpe_invocation_event partition 1: dial tcp: lookup KAFKA_HOSTMACHINE_IP on 127.0.0.11:53: no such host" source="kafka_exporter.go:262"
time="2018-11-30T10:42:15Z" level=error msg="Cannot get oldest offset of topic cpe_device_event partition 1: dial tcp: lookup KAFKA_HOSTMACHINE_IP on 127.0.0.11:53: no such host" source="kafka_exporter.go:262"
time="2018-11-30T10:42:15Z" level=error msg="Cannot get oldest offset of topic cpe_invocation_event_reply partition 1: dial tcp: lookup KAFKA_HOSTMACHINE_IP on 127.0.0.11:53: no such host" source="kafka_exporter.go:262"
```

ps: we can speak Chinese, if it is necessary. 为了方便理解，我们也可以说中文交流。

**Comment by dannyfreak** [comment]
Hi, I have similar issue, but without docker. I'm running kafka-exporter from binary on my local machine, but I also get errors while fetching metrics:

`ERRO[1136] Cannot get current offset of topic dand partition 0: dial tcp: lookup mob-not114 on 192.168.8.1:53: no such host  source="kafka_exporter.go:284"
ERRO[1136] Cannot get current offset of topic dany partition 0: dial tcp: lookup mob-not114 on 192.168.8.1:53: no such host  source="kafka_exporter.go:284"
ERRO[1136] Cannot get oldest offset of topic dand partition 0: dial tcp: lookup mob-not114 on 192.168.8.1:53: no such host  source="kafka_exporter.go:296"
ERRO[1136] Cannot get oldest offset of topic dany partition 0: dial tcp: lookup mob-not114 on 192.168.8.1:53: no such host  source="kafka_exporter.go:296"`

**Comment by dannyfreak** [comment]
Ok, my issue was not related to exporter. I had problem with Kafka.

**Comment by yc576192** [comment]
请问这个问题最后是怎么解决的？

**Comment by akdj** [comment]
Sorry, I can't answer you now, because I have not my laptop with me and I forget the details.. I will send you the details this Friday

**Comment by akdj** [comment]
@yc576192 
你好
我的问题其实很简单； 是我不小心写错了ip地址  你把下面的 “KAFKA_HOSTMACHINE_IP” 改成你的machine的ip地址 就行了
```
version: '2.0'

services:
  zookeeper_service:
    image: docker.rd.softathome.com/zookeeper/wurstmeister/zookeeper:3.4.9
    container_name: zookeeper
    hostname: zookeeper_service
    ports:
      - "2181:2181"
      - "7778:7778"

  kafka_service:
    image: docker.rd.softathome.com/kafka/wurstmeister/kafka:2.1.1
    container_name: kafka
    ports:
      - "9094:9094"

    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://**KAFKA_HOSTMACHINE_IP**:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper_service:2181"
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "my_topic:5:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      EXTRA_ARGS: "-javaagent:/opt/jmx/jmx_prometheus_javaagent-0.3.1.jar=7778:/opt/jmx/jmx_config.yml"
    volumes:
      - /home/jmx_prometheus_javaagent-0.3.1.jar:/opt/jmx/jmx_prometheus_javaagent-0.3.1.jar
    depends_on:
      - zookeeper_service
```
